unjs/listhen

test/index.test.ts
`new Error('')` make an error by
```
Error message should not be an empty string. `eslintunicorn/error-message`
```
I changed empty string to plain "Error".
=> chore: silent errors change empty string to "Error"

src/lib/open/index.ts
Hopefully fixes nuxt/framework#4495
I think there was a mistake when inlining `is-wsl` 3c2948f7432fb29c7cb9d020c20a7bb5cd83b253, `isWsl` in inlined version is a function, thus `isWsl == true`. Also a leftover copy paste typo.
=> fix: properly invoke isWsl as a function

src/index.ts
The API for `os.networkInterfaces()` changed in the version 18 of nodejs and now the values returned for the family is either 4 (for IPv4) or 6 (for IPv6).
https://nodejs.org/dist/latest-v18.x/docs/api/os.html#osnetworkinterfaces
=> feat: support new `networkInterfaces` for node.js >= 18

README.md
The first argument of `listen` function is `http.RequestListener` :)
https://github.com/unjs/listhen/blob/670eb9ebd759013cdd08470552f1379a5b6c2dad/src/index.ts#L55
=> docs: fix wrong argument

src/index.ts
what port is available depends on the hostname we're checking, but we were always checking localhost, even when we were listening on another port
See https://github.com/nuxt/framework/issues/6322.
=> fix: pass hostname to `getPort` as well

src/index.ts, test/index.test.ts
=> fix: pass port options object to `getPort`

src/index.ts, test/index.test.ts
=> fix: add default portRange

package.json
Currently `listhen` depends on `ip-regex` which is ESM-only. We could downgrade to a lower version of that package, but assuming we are using it, using listhen in a CJS context will throw this error:
```bash
[14:51:03]  ERROR  require() of ES Module /project/ip-regex@5.0.0/node_modules/ip-regex/index.js from /project/listhen@1.0.4/node_modules/listhen/dist/chunks/cert.cjs not supported.
Instead change the require of index.js in /project/listhen@1.0.4/node_modules/listhen/dist/chunks/cert.cjs to a dynamic import() which is available in all CommonJS modules.
Instead change the require of index.js in node_modules/.pnpm/listhen@1.0.4/node_modules/listhen/dist/chunks/cert.cjs to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> …
```
=> build: remove non existing `cjs` dist from `exports`

README.md, bin/listhen.mjs, package.json, pnpm-lock.yaml, src/_utils.ts, src/cli.ts, src/types.ts, src/watch.ts, tsconfig.json
Resolves #3
Support `listhen` CLI with:
- All possible options
- Dev watcher for auto reload
- Typescript and ESM support powered by jiti
=> feat: `listhen` cli

package.json, pnpm-lock.yaml, src/server/watcher.ts
Resolve issues with non node.js environments support such as stackblitz
https://github.com/parcel-bundler/watcher/issues/99#issuecomment-1659296504
=> fix(watcher): use `@parcel/watcher-wasm` for non node.js environment compatibility

test/cert.test.ts
This PR fixes an order miss match of the variables used in 2 tests. The check should actually check if the certificate is signed with the CA, and not if the CA is signed with the certificate, since the CA is self signed.
=> test: fix order mismatch

src/server/dev.ts, tsconfig.json
=>  fix(dev): try to resolve h3 from user `node_modules` first

package.json, pnpm-lock.yaml, src/listen.ts, src/types.ts
close #87
This PR also expose new utils `getURLs` for structure data of the URLs, so the user could render URLs in their own format if needed.
=> feat: print qr code for public address

package.json, pnpm-lock.yaml, src/server/watcher.ts
https://github.com/parcel-bundler/watcher/issues/99#issuecomment-1663191918
=> perf(dev): use `@parcel/watcher` whenever available

src/cli.ts, src/listen.ts, src/types.ts
resolves #88
This PR introduces a new `public` option (available as `--host` cli flag implicitly with vite cli consistancy) that controls whether by default we should listen to the public network interfaces or not.
If the option is not explicitly being set, we infer it first by checking (explicit) `hostname` if being `localhost` to disable and then fallback to env check and only enable public by default for production (more compatibility) and disable for development (more security).
I suppose this is a safe nonbreaking change especially since we keep production behavior as-is, support and show `--host` flag and anyway main consumers (nuxt and nitro) are introducing this feature in the non major version. But also open to make development default and release a major version if too much …
=> feat: `public` option and `--host` flag to disable network expose in development by default

src/_utils.ts, src/cli.ts, src/listen.ts, src/server/dev.ts, src/server/watcher.ts, src/types.ts
This PR enables an experimental behavior where as we auto-detect publicURL for stack blitz environment and show it in CLI output. 
This is a really hacky implementation implicitly based on internal behavior and environment variables (and naming) of stackblitz. I will have to check with their team how to improve (or remove it!)
https://stackblitz.com/~/github.com/unjs/listhen/pull/99
=> feat: stackblitz auto url detection (experimental)

test/setup.ts
This changes are not necessary, but maybe helpful for understanding of TLS certification and later testing. Also a fix is included (missing await).
The ca certificate and key are also written to `test/.tmp/certs/` and a certificate chain file (`test/.tmp/certs/cert.chain.pem`) is created.
=> fix(test): setup

pnpm-lock.yaml, src/_utils.ts, src/listen.ts
This PR improves the options handling for public hosts.
If `public` is not explicitly provided, we infer it in this order:
- `hostname` is explicitly localhost ? `false`
- `hostname` is explicitly anyhost range ? `true`
- `--host` flag provided (any value)? `true` (this is for CLI auto compatibility)
- production env ? `true`
- `false`
Listhen also shows smart warnings if options are used wrongly together:
- Public enabled and hostname is localhost:
- Show a warning that it is not going to listhen to anything public
- Fix internal `public` option to `false`
- Public is disabled and hostname is anyhost:
- Show a warning that public config is going to be disabled
- Force listen to `localhost` to avoid security implications
**Note:** Tunnel is a separate concept from public. One might choose …
=> fix: better options handling for public host

src/cli.ts
Handle description and explicitly for `--host` arg when is set true, to set host as anyhost
=> fix(cli): handle `--host` with boolean value

src/_utils.ts, src/listen.ts
Reports in https://github.com/nuxt/cli/issues/109
Windows IP stack can confuse for resolving `localhost` between IPv4 and IPv6 stacks.
For more safety, i also changed to prefer IPv4 anyhost (`0.0.0.0`) by default for windows. (It can be always overridden by users using `hostname` and `HOST`)
=> fix: use ipv4 for windows and wsl default hosts

src/lib/wsl.ts
Resolves #123
`getWslDrivesMountPoint` was returning a function, which then send to `childProcess.span`, which results in an error:
=> fix: open browser on wsl

src/_utils.ts, src/listen.ts
Since we had defaulted the host from anyhost to local, there had been several performance issues often either related to the ipv4/ipv6 dual stack or isolated envs (docker and WSL)
With #119 listen changed to prefer ipv4 stack `127.0.0.1` for Windows and WSL, however, it introduced performance regressions for Windows users when users type in `localhost` in the browser (it takes time from OS to first try `::1` as ipv6 localhost and falling back to `127.0.0.1`).
This PR tries to make behavior more reasonable:
- For Windows, same as MacOS and Linux listen on. My tests showed `localhost` perfectly works fast in different scenarios
- For wsl and docker, always use `""` (anyhost). These are by default isolated environments and need to be exposed by their runtime. Listening on all available …
=> perf: imprve default host for windows, docker and wsl

src/server/dev.ts
When running [ipx](https://github.com/unjs/ipx)'s `pnpm run dev` following environments, failed to import `h3Entry` in `createDevServer`.
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Package Manager:  pnpm@8.10.2
```
pnpm run dev 
> ipx@2.0.2 dev C:\Users\......\github.com\unjs\ipx
> listhen -w playground
ERROR  Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```
=> fix(dev): fix absolute paths import on windows

README.md
was testing out the project with h3 found 
`` [h3] Implicit event handler conversion is deprecated. Use `eventHandler()` or `fromNodeMiddleware()` to define event handlers.  ``
in the hello world example
- [x ] I have updated the documentation accordingly.
=> docs: update h3 example

.npmrc, README.md, package.json, playground/index.ts, pnpm-lock.yaml, src/cli.ts, src/listen.ts, src/server/dev.ts, src/server/watcher.ts, src/types.ts
This PR adds experimental WebSocket support.
The new `ws` option can be enabled via options or CLI. When set via options and is a function, will be used as normal Node.js upgrade handler.
When is an object, listhen will use [crossws](https://github.com/unjs/crossws) API to listen on the hooks.
When is `true` (set by CLI), listhen dev server will support WebSocket with HMR (using a hooks proxy)
=> feat: experimental websocket support

src/server/_resolver.ts
=> fix(dev): normalize paths with `pathe`
